export const data = [
  {
    CaseId: "C001",
    CaseTitle: "Property Dispute",
    CaseType: "Litigation",
    ClientId: "CL001",
    ClientName: "John Doe",
    Lawyers: ["Jane Smith"],
    priority: "High",
    CreatedOn: "2024-08-01",
    EstimatedEndDate: "2024-12-31",
    CaseStatus: "In Progress",
    CaseDescription: "Dispute over real estate ownership.",
    CaseNotes: "Filed in court, awaiting hearing.",
    ConsultationDate: "2024-08-05",
    ConsultationTime: "45:00",
    ConsultationType: "Physical",
    ConsultationAgenda: "Review case details, plan strategy.",
    fees: 5000,
  },
  {
    CaseId: "C002",
    CaseTitle: "Employment Contract Review",
    CaseType: "Contract Drafting",
    ClientId: "CL002",
    ClientName: "Alice Johnson",
    Lawyers: ["Michael Brown"],
    priority: "Medium",
    CreatedOn: "2024-08-15",
    EstimatedEndDate: "2024-09-15",
    CaseStatus: "Open",
    CaseDescription: "Review and revise employment contract.",
    CaseNotes: "Initial consultation complete.",
    ConsultationDate: "2024-08-17",
    ConsultationTime: "30:00",
    ConsultationType: "Virtual",
    ConsultationAgenda: "Review clauses, suggest revisions.",
    fees: 1500,
  },
  {
    CaseId: "C003",
    CaseTitle: "Defamation Lawsuit",
    CaseType: "Litigation",
    ClientId: "CL003",
    ClientName: "Michael Green",
    Lawyers: ["Sarah Lee"],
    priority: "Urgent",
    CreatedOn: "2024-09-01",
    EstimatedEndDate: "2024-11-30",
    CaseStatus: "In Progress",
    CaseDescription: "Suing for defamation in public statements.",
    CaseNotes: "Filed initial motion.",
    ConsultationDate: "2024-09-03",
    ConsultationTime: "60:00",
    ConsultationType: "Both",
    ConsultationAgenda: "Prepare for preliminary hearing.",
    fees: 10000,
  },
  {
    CaseId: "C004",
    CaseTitle: "Land Acquisition Notice",
    CaseType: "Legal Notice",
    ClientId: "CL004",
    ClientName: "Sophia White",
    Lawyers: ["Thomas Jackson"],
    priority: "Low",
    CreatedOn: "2024-07-25",
    EstimatedEndDate: "2024-12-01",
    CaseStatus: "On Hold",
    CaseDescription: "Acquisition notice for commercial land.",
    CaseNotes: "Pending client decision on response.",
    ConsultationDate: "2024-07-30",
    ConsultationTime: "25:00",
    ConsultationType: "Virtual",
    ConsultationAgenda: "Discuss notice and possible responses.",
    fees: 2000,
  },
  {
    CaseId: "C005",
    CaseTitle: "Contract Breach",
    CaseType: "Litigation",
    ClientId: "CL005",
    ClientName: "William Brown",
    Lawyers: ["Nancy Anderson"],
    priority: "High",
    CreatedOn: "2024-08-10",
    EstimatedEndDate: "2025-01-15",
    CaseStatus: "In Progress",
    CaseDescription: "Breach of service agreement.",
    CaseNotes: "Filing legal paperwork.",
    ConsultationDate: "2024-08-13",
    ConsultationTime: "50:00",
    ConsultationType: "Physical",
    ConsultationAgenda: "Gather documents, prepare filing.",
    fees: 7500,
  },
  {
    CaseId: "C006",
    CaseTitle: "Trademark Registration",
    CaseType: "Legal Consultation",
    ClientId: "CL006",
    ClientName: "Isabella Smith",
    Lawyers: ["Robert Williams"],
    priority: "Medium",
    CreatedOn: "2024-09-05",
    EstimatedEndDate: "2024-11-15",
    CaseStatus: "Open",
    CaseDescription: "Consultation on trademark registration process.",
    CaseNotes: "Reviewing documents.",
    ConsultationDate: "2024-09-10",
    ConsultationTime: "40:00",
    ConsultationType: "Virtual",
    ConsultationAgenda: "Explain trademark application process.",
    fees: 3000,
  },
  {
    CaseId: "C007",
    CaseTitle: "Divorce Settlement",
    CaseType: "Litigation",
    ClientId: "CL007",
    ClientName: "Emma Davis",
    Lawyers: ["Matthew Harris"],
    priority: "Urgent",
    CreatedOn: "2024-07-20",
    EstimatedEndDate: "2024-11-20",
    CaseStatus: "In Progress",
    CaseDescription: "Negotiation for divorce settlement.",
    CaseNotes: "Mediation in process.",
    ConsultationDate: "2024-07-25",
    ConsultationTime: "55:00",
    ConsultationType: "Physical",
    ConsultationAgenda: "Discuss settlement options.",
    fees: 9000,
  },
  {
    CaseId: "C008",
    CaseTitle: "Business Partnership Agreement",
    CaseType: "Contract Drafting",
    ClientId: "CL008",
    ClientName: "Olivia Martinez",
    Lawyers: ["Patricia Wilson"],
    priority: "Medium",
    CreatedOn: "2024-08-28",
    EstimatedEndDate: "2024-10-05",
    CaseStatus: "Open",
    CaseDescription: "Drafting a partnership agreement for new business.",
    CaseNotes: "Initial review of terms.",
    ConsultationDate: "2024-08-30",
    ConsultationTime: "35:00",
    ConsultationType: "Both",
    ConsultationAgenda: "Discuss partnership clauses.",
    fees: 4000,
  },
  {
    CaseId: "C009",
    CaseTitle: "Tenant Eviction",
    CaseType: "Litigation",
    ClientId: "CL009",
    ClientName: "James Wilson",
    Lawyers: ["Steven Roberts"],
    priority: "High",
    CreatedOn: "2024-08-18",
    EstimatedEndDate: "2024-11-01",
    CaseStatus: "In Progress",
    CaseDescription: "Eviction lawsuit against tenant.",
    CaseNotes: "Served tenant with notice.",
    ConsultationDate: "2024-08-20",
    ConsultationTime: "50:00",
    ConsultationType: "Physical",
    ConsultationAgenda: "Discuss eviction process.",
    fees: 6000,
  },
  {
    CaseId: "C010",
    CaseTitle: "Fraud Investigation",
    CaseType: "Legal Consultation",
    ClientId: "CL010",
    ClientName: "Ethan Moore",
    Lawyers: ["Lisa Johnson"],
    priority: "Urgent",
    CreatedOn: "2024-09-10",
    EstimatedEndDate: "2024-12-15",
    CaseStatus: "Open",
    CaseDescription: "Consultation on possible fraud within the company.",
    CaseNotes: "Reviewing financial documents.",
    ConsultationDate: "2024-09-12",
    ConsultationTime: "65:00",
    ConsultationType: "Both",
    ConsultationAgenda: "Investigate fraudulent transactions.",
    fees: 8000,
  },
  {
    CaseId: "C011",
    CaseTitle: "Intellectual Property Dispute",
    CaseType: "Litigation",
    ClientId: "CL011",
    ClientName: "Charlotte Walker",
    Lawyers: ["Daniel Adams"],
    priority: "High",
    CreatedOn: "2024-08-25",
    EstimatedEndDate: "2024-12-10",
    CaseStatus: "In Progress",
    CaseDescription: "Dispute over intellectual property rights.",
    CaseNotes: "Opposing party requested mediation.",
    ConsultationDate: "2024-08-28",
    ConsultationTime: "70:00",
    ConsultationType: "Virtual",
    ConsultationAgenda: "Discuss mediation strategy.",
    fees: 9500,
  },
  {
    CaseId: "C012",
    CaseTitle: "Personal Injury Claim",
    CaseType: "Litigation",
    ClientId: "CL012",
    ClientName: "Henry Edwards",
    Lawyers: ["Samantha Foster"],
    priority: "Urgent",
    CreatedOn: "2024-07-01",
    EstimatedEndDate: "2024-11-01",
    CaseStatus: "In Progress",
    CaseDescription:
      "Client seeking damages for personal injury from a car accident.",
    CaseNotes: "Filed for compensation claim.",
    ConsultationDate: "2024-07-05",
    ConsultationTime: "40:00",
    ConsultationType: "Physical",
    ConsultationAgenda: "Discuss settlement offer and next steps.",
    fees: 7000,
  },
  {
    CaseId: "C013",
    CaseTitle: "Lease Agreement Drafting",
    CaseType: "Contract Drafting",
    ClientId: "CL013",
    ClientName: "Chloe Cooper",
    Lawyers: ["Evelyn Turner"],
    priority: "Medium",
    CreatedOn: "2024-09-15",
    EstimatedEndDate: "2024-10-15",
    CaseStatus: "Open",
    CaseDescription: "Drafting a lease agreement for a commercial property.",
    CaseNotes: "Client reviewing draft.",
    ConsultationDate: "2024-09-18",
    ConsultationTime: "30:00",
    ConsultationType: "Both",
    ConsultationAgenda: "Review lease terms with client.",
    fees: 2500,
  },
  {
    CaseId: "C014",
    CaseTitle: "Family Business Dispute",
    CaseType: "Legal Consultation",
    ClientId: "CL014",
    ClientName: "Mason Wright",
    Lawyers: ["Benjamin Hughes"],
    priority: "Low",
    CreatedOn: "2024-08-12",
    EstimatedEndDate: "2024-12-20",
    CaseStatus: "On Hold",
    CaseDescription:
      "Consultation on resolving a dispute over a family business.",
    CaseNotes: "Waiting for further instructions from the client.",
    ConsultationDate: "2024-08-15",
    ConsultationTime: "55:00",
    ConsultationType: "Virtual",
    ConsultationAgenda: "Discuss possible legal approaches to resolve dispute.",
    fees: 4000,
  },
];
